import { useState } from 'react';
import type { User } from '../../services/auth/auth.types';
import type { ToolPanel } from './SchoolObjects';
import { news } from '../../data/news';
import { capsules } from '../../data/didYouKnow';
import { resources } from '../../data/resources';
export const panelTitles: Record<ToolPanel, string> = { profile: 'Tu carné estudiantil', favorites: 'Tus favoritos', news: 'Noticias destacadas', visits: 'Sitios más visitados', facts: 'Sabías que…', rating: 'Califícame' };
export function ToolContent({ panel, user, favorites, counts, onSelect, onToggle, onSignOut }: { panel: ToolPanel; user: User; favorites: string[]; counts: Record<string, number>; onSelect: (id: string) => void; onToggle: (id: string) => void; onSignOut: () => void }) {
  const [capsule, setCapsule] = useState(0);
  const [rating, setRating] = useState(''); const [submitted, setSubmitted] = useState(false);
  if (panel === 'profile') return <><p className="panel-kicker">PERFIL DE LA CUENTA · MOCK</p><dl className="profile-data"><dt>Nombre</dt><dd>{user.name}</dd><dt>Rol</dt><dd>{user.role}</dd><dt>Centro educativo</dt><dd>{user.institution}</dd></dl><details><summary>Acerca de Mochila Digital</summary><p>Prototipo frontend inspirado en una mochila escolar. Todos los datos de perfil y las noticias son ficticios. No existe autenticación institucional ni conexión con servicios privados del MEP.</p></details><button className="secondary-button" onClick={onSignOut}>Cerrar sesión de demostración</button></>;
  if (panel === 'favorites') return <><p className="muted">Guardados únicamente en este navegador.</p>{favorites.length ? <ul className="panel-list">{resources.filter(r => favorites.includes(r.id)).map(r => <li key={r.id}><button className="list-button" onClick={() => onSelect(r.id)}>{r.name} <span aria-hidden="true">→</span></button><button className="remove-favorite" aria-label={`Quitar ${r.name} de favoritos`} onClick={() => onToggle(r.id)}>Quitar</button></li>)}</ul> : <div className="empty-state"><span aria-hidden="true">☆</span><h3>Tu primer favorito te espera</h3><p>Seleccioná un cuaderno y elegí “Agregar a favoritos”.</p></div>}</>;
  if (panel === 'news') return <><p className="muted">Contenido simulado · No son anuncios oficiales.</p>{news.map(item => <article className="news-entry" key={item.id}><time dateTime={item.date}>{new Intl.DateTimeFormat('es-CR', { day:'numeric', month:'long', year:'numeric', timeZone:'UTC' }).format(new Date(`${item.date}T12:00:00Z`))}</time><h3>{item.title}</h3><p>{item.summary}</p>{item.url && <a href={item.url} target="_blank" rel="noopener noreferrer">Leer noticia (sitio externo, pestaña nueva)</a>}</article>)}</>;
  if (panel === 'visits') { const ranking = resources.filter(r => (counts[r.id] ?? 0) > 0).sort((a,b) => counts[b.id] - counts[a.id]); return <><p className="muted">Aperturas registradas en este navegador. No son estadísticas institucionales.</p>{ranking.length ? <ol className="panel-list">{ranking.map(r => <li key={r.id}><button className="list-button" onClick={() => onSelect(r.id)}>{r.name}<span>{counts[r.id]} {counts[r.id] === 1 ? 'visita' : 'visitas'}</span></button></li>)}</ol> : <div className="empty-state"><h3>Tu recorrido empieza ahora</h3><p>Abrí un sitio desde un cuaderno para registrar tu primera visita.</p></div>}</>; }
  if (panel === 'facts') return <><div className="capsule" aria-live="polite"><p className="panel-kicker">CÁPSULA {capsule + 1} DE {capsules.length}</p><h3>{capsules[capsule].title}</h3><p>{capsules[capsule].text}</p></div><div className="panel-actions"><button className="secondary-button" disabled={capsule === 0} onClick={() => setCapsule(c => c - 1)}>← Anterior</button><button className="primary-button" disabled={capsule === capsules.length - 1} onClick={() => setCapsule(c => c + 1)}>Siguiente →</button></div></>;
  return <><p className="muted">Valoración de demostración. No se envía ni se guarda información.</p>{submitted ? <p role="status" className="rating-success">¡Gracias por probar la experiencia! Tu valoración fue simulada.</p> : <form onSubmit={e => { e.preventDefault(); setSubmitted(true); }}><fieldset className="rating-field"><legend>¿Cómo fue tu experiencia?</legend>{[1,2,3,4,5].map(n => <label key={n}><input type="radio" name="rating" value={n} checked={rating === String(n)} onChange={e => setRating(e.target.value)} required/><span>{n} ★</span><span className="sr-only">{n === 1 ? ' Muy mala' : n === 5 ? ' Muy buena' : ''}</span></label>)}</fieldset><button className="primary-button" type="submit" disabled={!rating}>Simular valoración</button></form>}</>;
}
